#!/usr/bin/env bash
#set -e

test $# -le 1 || { echo "synopsis: git forward-port [BRANCH]"; exit 1; }

B=${1:-$(git previous-branch)}
H=$(git describe --always "$B")

git merge --no-ff --no-commit -m "[MERGE] forward port branch $B up to $H" "$B"
git diff --cached --shortstat
